general {
	disable_loading_bar = true
	hide_cursor = true
}

background {
	monitor =
	path = /home/rezar2p/Downloads/wallhaven-zyxvqy_1366x768.png
	blur_passes = 1
	blur_size = 2
	noise = 0.0117
	contrast = 1.0
	brightness = 1.0
	vibrancy = 0.1696
	vibrancy_darkness = 0.0
}

input-field {
	monitor =
	size = 280, 50
	outline_thickness = 2
	dots_size = 0.2
	dots_spacing = 0.2
	dots_center = true
	outer_color = rgba(151515aa)
	inner_color = rgba(20202099)
	font_color = rgb(cdd6f4)
	fade_on_empty = false
	placeholder_text = <i>Enter Password...</i>
	hide_input = false
	check_color = rgb(f9e2af)
	fail_color = rgb(f38ba8)
	position = 0, -80
	halign = center
	valign = center
}

label {
	monitor =
	text = cmd[update:1000] echo "$(date +'%H:%M')"
	color = rgb(cdd6f4)
	font_size = 80
	font_family = Sans
	position = 0, 140
	halign = center
	valign = center
}

label {
	monitor =
	text = cmd[update:1000] echo "$(date +'%A, %d %B %Y')"
	color = rgb(bac2de)
	font_size = 24
	font_family = Sans
	position = 0, 60
	halign = center
	valign = center
}
