# Main Hyprland config (modular)
# Each section is split into a dedicated file for easier maintenance.

source = ~/.config/hypr/conf/00-variables.conf
source = ~/.config/hypr/conf/10-monitor.conf
source = ~/.config/hypr/conf/20-autostart.conf
source = ~/.config/hypr/conf/30-look-feel.conf
source = ~/.config/hypr/conf/40-input.conf
source = ~/.config/hypr/conf/50-keybinds.conf
source = ~/.config/hypr/conf/60-window-workspace.conf
